#!/usr/bin/env node

// see lib/main.js for info

var config = {
        inFile: 'data.js'
      , outFile: 'data-min.js'
      , githubLastPushCutoffMonths: 48 // for now—need to tweak this later
      , sizeExceptions: [
            'Backbone'
          , 'Zepto'
        ]
      , errorCountThreshold: 10
      , verbose: process.argv.indexOf('-v') != -1
      , quiet: process.argv.indexOf('-q') != -1
    }
  , ghAuth = require('./lib/ghauth')
  , main = require('./lib/main')
  , stats = require('./lib/stats')

ghAuth(config, function () {
  (process.argv.indexOf('-s') != -1 ? stats : main).create(config).start()
})