#!/usr/bin/env node

// see lib/main.js for info

var config = {
        inFile: 'data.js'
      , outFile: 'data-min.js'
      , sizeExceptions: [
            'Backbone'
          , 'Zepto'
        ]
      , verbose: process.argv.indexOf('-v') != -1
    }
  , main = require('./lib/main')
  , stats = require('./lib/stats')

!(process.argv.indexOf('-s') != -1 ? stats : main).create(config).start()

