#!/usr/bin/env node

// see lib/main.js for info

var inFile = 'data.js'
  , outFile = 'data-min.js'
  , main = require('./lib/main')
  , stats = require('./lib/stats')

!(process.argv.indexOf('-s') != -1
  ? stats.create(inFile)
  : main.create(inFile, outFile, process.argv.indexOf('-v') != -1)
).start()

